Hermione 1017
gemini-testing/playwright-selenium-oauth pull request #1
Opened 2023-06-19 10:08 UTC by rprovodenko

2023-06-19 12:27 UTC, KuznetsovRoman commented on src/setup.test.ts
> +        delete process.env.SELENIUM_REMOTE_HEADERS;
Теперь эта секция съедает две переменные среды.

Может, сохранять значение этих полей внутри `describe` и в `afterEach` восстанавливать оригинальные?

2023-06-19 12:28 UTC, rprovodenko commented on src/setup.test.ts
> +        delete process.env.SELENIUM_REMOTE_HEADERS;
> Теперь эта секция съедает две переменные среды.

что ты имеешь в виду? тесты запускаются в отдельном процессе, который выходит как только тесты заканчиваются. Удаление этих переменных удаляет их только в рамках процесса, это не распространяется на твою бэш сессию там или zsh

2023-06-19 12:32 UTC, KuznetsovRoman commented on src/setup.test.ts
> +global.console = <Console>(<unknown>{ warn: jest.fn(), error: jest.fn(), log: jest.fn() });
https://stackoverflow.com/a/56677834

2023-06-19 12:44 UTC, KuznetsovRoman commented on src/setup.test.ts
> +        delete process.env.SELENIUM_REMOTE_HEADERS;
**До** выполнения этой секции переменная среды может какая-то и стояла, а вот будет ли она **после** - зависит от того, какой тест в ней выполнится последним (потому что какие-то тесты все таки устанавливают ее, при этом в `afterEach` ты не убираешь то, что поставил во время выполнения юнита). По итогу получается, что эта секция изменяет состояние, что в принципе `bad practice`, и это в теории может привести к тяжело отлавливаемому падению теста из другого файла, потому что какой-то из тестов этой секции установил какое-то значение этим переменным среды.

Насколько это плохо, и произойдет ли такая ситуация на самом деле - понятия не имею, на фиксе не настаиваю, просто уточняю, что такое теоретически может произойти

2023-06-19 12:58 UTC, rprovodenko commented on src/setup.test.ts
> +        delete process.env.SELENIUM_REMOTE_HEADERS;
а, ты хочешь сказать, что в этом пакете будет какой-то тест, который будет зависеть от переменной этой окружающей среды. Это актуально только когда ты используешь эту опцию: https://jestjs.io/docs/cli#--runinband 

> отлавливаемому падению теста из другого файла

джест запускает каждый тест файл как отдельный процесс с использованием пула воркеров (по дефолту, без опции run in band, которая используется в экзотических ситуациях, и юзер должен понимать что она так работает)

В общем и целом, когда ты используешь джест (не мока, в мока - да, такая проблема была, но это допотопная технология), тебе не нужно беспокоится о зависимостях сетапа между тест файлами

2023-06-20 12:51 UTC, DudaGod requested changes
Еще осталось немного вопросов

2023-06-20 12:51 UTC, DudaGod commented on .eslintrc.js
> +};
В конце строки нет отступа (об этом gh сообщает).

2023-06-20 12:51 UTC, DudaGod commented on .eslintrc.js
> +                "@typescript-eslint/no-empty-function": "off",
А зачем это правило отключать? Пустые функции же зло.

2023-06-20 12:51 UTC, DudaGod commented on .eslintrc.js
> +                "@typescript-eslint/no-explicit-any": "off",
Я за то, чтобы явно приводить типы и вообще не использовать any.

2023-06-20 12:51 UTC, DudaGod commented on README.md
>  # A library for OAuth Selenium authentication in PlayWright
Обычно в первом хедере же пишут название библиотеки. А затем ниже описывают для чего она нужна. Мы все так наши пакеты оформляем.

2023-06-20 12:51 UTC, DudaGod commented on README.md
> +  await setup();
Тут же получается пример не валидный и он работать не будет, так как токен не передается. Я бы сразу тут указывал варианты с конфигурацией токена, а не описывал их в отдельном разделе ниже.

2023-06-20 12:51 UTC, DudaGod commented on README.md
> +- `await setup({tokenFilePath: /path/to/my/token})`, where `token` is a text file containing the token
`token` -> `tokenFilePath`

2023-06-20 12:51 UTC, DudaGod commented on README.md
> +- specifying via env variable: `export PLAYWRIGHT_SELENIUM_OAUTH_TOKEN=<my-token>`
А где переменная окружения для пути к файлу? Ну и я бы указывал пример с `process.env` или `PLAYWRIGHT_SELENIUM_OAUTH_TOKEN=<my-token> npx playwright test`

2023-06-20 12:51 UTC, DudaGod commented on README.md
> +await setup({help: "You can generate the token here: https://here/the/user/may/get/his/token"})
Я бы тут сразу и `tokenFilePath` указал.

2023-06-20 12:51 UTC, DudaGod commented on package.json
> +    "description": "Plugin for convenient setting of authorization OAuth token header for PlayWright - works with Selenium",
Это же не плагин (в pwt нет плагинов), а просто тулза или хелпер.
А почему просто не указать `... token header for Selenium browsers`?

2023-06-20 12:51 UTC, DudaGod commented on package.json
> +        "eslint-config-prettier": "^8.8.0"
А почему эти пакеты попали в `dependencies`? Они должны быть в `devDependencies` же.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.ts
> +const tokenEnvVarialbe = "PLAYWRIGHT_SELENIUM_OAUTH_TOKEN";
Нужна еще переменная окружения для файла. Так как именно его используют ребята из одного наших сервисов в CI (с hermione).

2023-06-20 12:51 UTC, DudaGod commented on src/setup.ts
> +    if (options?.token && options.tokenFilePath) {
А зачем вопросик в этой записи - `options?.token`?

2023-06-20 12:51 UTC, DudaGod commented on src/setup.ts
> +        console.warn(`playwright-selenium-oauth: both "token" and "tokenFilePath" have been provided, using "token"`);
А зачем тут варнинг кидать? Ведь ниже пользователь может указать переменную окружения. В итоге будет кейс, что он валиадно указал переменную окружения, но получит варнинг.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.ts
> +        throw new Error(`playwright-selenium-oauth: error parsing ${headersEnvVariable}. ${e}`);
А для чего в каждой ошибке писать название инструмента? Ведь по стектрейсу итак будет понятно откуда она вылетела. Уточню, что просто интересуюсь и особо не против таких ошибок.

Подобная строка с названием инструмента встречается уже не в первый раз в коде. Предлагаю избавится от дублирования и унести ее генерацию в отдельный файл `utils`. В котором было бы неплохо брать название из `package.json`.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.ts
> +    const tokenFromEnv = process.env[tokenEnvVarialbe];
Переменные окружения нужно обрабатывать первыи. У них должен быть приоритет перед обычными опциями.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.ts
> +}
Вообще по красоте конечно будет за собой почистить. Т.е. вернуть функцию, которая после себя восстановит `process.env` (что-то типа `teardown`). Я такой подход в туннелере юзаю.

Но не настаиваю, так как смысла в таком конечно не очень много будет.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.ts
> +        const path = options.tokenFilePath;
А зачем так? Можно же просто передать `options.tokenFilePath` и не тратить лишнюю строку кода. Вроде при этом код в читабельности не теряет.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.ts
> +        throw new Error(`playwright-selenium-oauth: token is empty or only contains spaces`);
Я бы явно не писал, что он содержит пробелы. Просто написал бы, что он пустой.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.ts
> +        console.warn(`playwright-selenium-oauth: there is already an Authorization header, not doing anything.`);
Я бы `not doing anything` удалил, ну или хотя бы изменил `do nothing`, который читается более понятно.

2023-06-20 12:51 UTC, DudaGod commented on src/test-fixtures/setup-testtoken-empty
> +
А эти фикстуры у тебя сейчас в папку `build` не попадают случайно? Судя по tsconfig попадают, так как не вижу `exclude` для них.

2023-06-20 12:51 UTC, DudaGod commented on tsconfig.spec.json
> +    "compilerOptions": {}
Если ты `outDir` убрал. То зачем тогда вообще этот конфиг? Можно было бы удалить.

2023-06-20 12:51 UTC, DudaGod commented on src/read-token.ts
> +        console.error(e);
А зачем тут этот `console.error`? Почему не достаточно просто ошибку ниже кинуть?

2023-06-20 12:51 UTC, DudaGod commented on src/read-token.ts
> +        throw new Error(`playwright-selenium-oauth: error reading token from file, path: ${path}. ${e}. ${help ?? ""}`);
Сейчас выглядит, что тут жирная ошибка в одну строку будет. Почему бы не отобразить сначала нашу информацию + `help`. А затем ниже с переводом строки - `Original error: e`?

2023-06-20 12:51 UTC, DudaGod commented on src/read-token.ts
> +    console.log(`playwright-selenium-oauth: reading token at ${path}`);
А этот лог для чего? Предлагаю ничего такого не выводить. Если сильно хочется, то нужно использовать хотя бы библиотеку `debug`. Чтобы пользователь мог самостоятельно определить нужен ему этот лог или нет.

Большинство пользователей ничего лишнего не хотят видеть.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.test.ts
> +global.console = <Console>(<unknown>{ warn: jest.fn(), error: jest.fn(), log: jest.fn() });
Ну да, тут правильно все эти методы мокать.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.test.ts
> +        (<jest.Mock>(<unknown>global.console.error)).mockClear();
Зачем? У тебя же jest.config.js выставлена опция - `clearMocks: true`. Т.е. явно такие очистки делать не нужно.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.test.ts
> +        expect(process.env.SELENIUM_REMOTE_HEADERS).toBe(`{"Authorization":"OAuth mytoken"}`);
У нас тетсы обычно пишутся с использованием паттерна AAA (arrange, act, assert). Следуя этому паттерну код тестов должен быть разделен на понятные блоки кода. Про данный подход можно почитать например тут - https://robertmarshall.dev/blog/arrange-act-and-assert-pattern-the-three-as-of-unit-testing/

2023-06-20 12:51 UTC, DudaGod commented on src/setup.test.ts
> +            `"playwright-selenium-oauth: error reading token from file, path: /i/do/not/exist. Error: ENOENT: no such file or directory, open '/i/do/not/exist'. i don't need your help"`,
В итоге получается очень непонятная ошибка. Выше писал как мне кажется она должна выглядеть.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.test.ts
> +    });
Нет теста, что переменная окружения имеет больший приоритет, чем строка.

2023-06-20 12:51 UTC, DudaGod commented on src/setup.test.ts
> +            `"playwright-selenium-oauth: "token" or "tokenFilePath" or PLAYWRIGHT_SELENIUM_OAUTH_TOKEN env var must be provided"`,
А почему не `rejects.toThrow`? Выглядит короче и умеет regexp принимать. Как по мне нет особого смысла проверить текст ошибки один в один. Главное проверить, что вылетела ожидаемая ошибка.

Но не настаиваю. Можешь и так оставить.

2023-06-20 12:51 UTC, DudaGod commented on src/test-fixtures/setup-testtoken-empty
> +
Ну и я бы эти файлы назвал просто `token` и `empty-token`. Непонятно зачем добавлять `setup-test`.

2023-06-20 13:56 UTC, rprovodenko commented on src/setup.ts
> +    if (options?.token && options.tokenFilePath) {
потому что `options` optional

2023-06-20 13:58 UTC, rprovodenko commented on src/setup.ts
> +        console.warn(`playwright-selenium-oauth: both "token" and "tokenFilePath" have been provided, using "token"`);
ворнинги он получает если `token` и `tokenFilePath` оба не являются falsy значениями, т.е. он задал их обоих

2023-06-20 14:00 UTC, rprovodenko commented on src/setup.ts
> +        throw new Error(`playwright-selenium-oauth: error parsing ${headersEnvVariable}. ${e}`);
> А для чего в каждой ошибке писать название инструмента? Ведь по стектрейсу итак будет понятно откуда она вылетела.

Рома валидный коммент оставил, что ошибку или лог нужно быстро уметь идентифицировать по названию. Обычно для этого используют логгеры. Здесь имо слишком маленький проект, чтобы использовать логер (мне было лень добавлять).

В джаваскрипт мире не все ошибки дают meaningful стек трейс, из-за event loop и асинхронности.

Про util согласен. Но не согласен, что нужно брать из package.json - импортить извне src это неудобно. Может я все-таки логгер добавлю тогда, или да, конструктор именных мессаг.

2023-06-20 14:02 UTC, rprovodenko commented on src/setup.ts
> +    const tokenFromEnv = process.env[tokenEnvVarialbe];
Не согласен. Не буду спорить, если в яндексе так принято, но если такой конвенции нет, то все наоборот. Очевидные аргументы имеют приоритет над неявными

2023-06-20 14:04 UTC, rprovodenko commented on src/setup.ts
> +}
ты не там коммент оставил, хотел в тест файле? я уже написал почему в джесте это бессмысленно и так не делают

2023-06-20 15:49 UTC, DudaGod commented on src/setup.ts
> +}
Я тут и хотел коммент оставить. В pwt мире `globalSetup` может быть описан следующим образом:
```
export default async function globalSetup() {
  // setup section
  const teardownFn = await setupSomething();

  return async () => {
    await teardownFn();
  };
}
```

Т.е. функция `setup` может возвращать какую-то другую функцию при вызове которой будет выполнятся `teardown`. В данном случае очистка окружения. Сам pwt функцию которую вернет `globalSetup` выполнит в конце выполнения всех тестов.

2023-06-20 16:02 UTC, DudaGod commented on src/setup.ts
> +    const tokenFromEnv = process.env[tokenEnvVarialbe];
А почему не согласен? Например при использовании данной библиотеки я указываю путь до файла с токеном на своей fs. Но при запуске в CI мне тесты запускаются на другой машинке с другой fs и выполнение происходит вообще от имени робота. Соответственно токен нужен другой. Каким образом я смогу переопределить путь до него?

В наших библиотеках мы обычно используем следующий приоритет:
- env
- cli
- config

Вижу, что у amazon немного другая очередность - https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#precedence. Но у них env переменные тоже имеют больший приоритет чем конфиг.

В данном случае можно сказать, что у нас же нет конфига и мы передаем опции просто в функцию. Но необходимость иметь возможность переопределить что-то в CI все еще остается. И обычно это делается через переменные окружения.

2023-06-20 16:07 UTC, DudaGod commented on src/setup.ts
> +    if (options?.token && options.tokenFilePath) {
А почему тогда вопросика нет при записи `options?.tokenFilePath`? Ну и `options` можно же по дефолту приводить к пустому объекту.

2023-06-20 16:41 UTC, DudaGod commented on src/setup.ts
> +        console.warn(`playwright-selenium-oauth: both "token" and "tokenFilePath" have been provided, using "token"`);
А точно, провтыкал. Но я бы все равно ошибку кидал, чтобы пользователь определился какой из вариантов он хочет использовать. Иначе сейчас он может передать 2 опции, затем не увидеть варнинг (большинство их не видит) и не поймет какой из них вообще применится и имеет больший приоритет.

2023-06-21 16:54 UTC, DudaGod commented on README.md
> +- specifying via env variable: `export PLAYWRIGHT_SELENIUM_OAUTH_TOKEN=<my-token>`
Сегодня ковырялся в исходниках pwt и заметил, что они в основном называют переменные окружения вот так - `PW_...`. Ну и кстати если в pwt для selenium переменные окружения называются просто - `SELENIUM_HEADERS` или `SELENIUM_URL`. То может данную переменную окружения тоже назовем просто `SELENIUM_OAUTH_TOKEN`? Т.е. чтобы было консистентно. Что думаешь?

2023-06-22 07:05 UTC, rprovodenko commented on .eslintrc.js
> +                "@typescript-eslint/no-empty-function": "off",
https://github.com/gemini-testing/playwright-oauth/pull/2#discussion_r1231925737

2023-06-22 07:05 UTC, rprovodenko commented on .eslintrc.js
> +                "@typescript-eslint/no-explicit-any": "off",
https://github.com/gemini-testing/playwright-oauth/pull/2#discussion_r1231925737

2023-06-22 07:16 UTC, rprovodenko commented on src/setup.test.ts
> +        expect(process.env.SELENIUM_REMOTE_HEADERS).toBe(`{"Authorization":"OAuth mytoken"}`);
ты можешь объяснить в чем эти тесты не следуют этому паттерну? в том что пустых строк нет или что?

2023-06-22 07:19 UTC, rprovodenko commented on src/setup.test.ts
> +            `"playwright-selenium-oauth: "token" or "tokenFilePath" or PLAYWRIGHT_SELENIUM_OAUTH_TOKEN env var must be provided"`,
потому что снэпшоты автоматически генерируются

2023-06-22 07:26 UTC, rprovodenko commented on src/setup.ts
> +    const tokenFromEnv = process.env[tokenEnvVarialbe];
ну здесь же нет конфига. Здесь есть код напрямую. Юзер прямо в коде пишет способ аутентификации. Это не конфиг файл

2023-06-22 07:28 UTC, rprovodenko commented on src/setup.ts
> +    if (options?.token && options.tokenFilePath) {
потому что type inference. логический AND выходит если левая часть falsy

2023-06-22 07:29 UTC, rprovodenko commented on src/setup.ts
> +        const path = options.tokenFilePath;
в яндексе очень дорогие строки кода?

2023-06-22 08:34 UTC, rprovodenko commented on src/read-token.ts
> +        console.error(e);
оно по разному приводится к стринге (во втором случае без стек трейса по идее). 
<img width="534" alt="image" src="https://github.com/gemini-testing/playwright-selenium-oauth/assets/60982217/efff7879-fa6f-4434-9bd5-139a41af9271">

2023-06-22 08:41 UTC, rprovodenko commented on src/read-token.ts
> +    console.log(`playwright-selenium-oauth: reading token at ${path}`);
ну выбирая между большим логгированием (критичных вещей) и меньшим, нужно всегда выбирать большее. согласен, дебаг левел в идеале нужен - просто библиотека такая микроскопическая что не хотелось сюда добавлять логгер. окей, давай удалю, если ты настаиваешь. пусть юзеры помучаются)

особенно в ci будет весело дебажить почему аутентификация не работает)

2023-06-22 08:47 UTC, rprovodenko commented on src/setup.ts
> +}
так tearDown же вызывается перед выходом процесса. Зачем там что-то делать - мы же только environment в рамках процесса изменяем. tearDown сделано для того, чтобы внешние ресурсы подчищать

2023-06-22 08:48 UTC, rprovodenko commented on src/test-fixtures/setup-testtoken-empty
> +
тайпскрипт не копирует статику, если она не импортируется через импорты (не чтения файла, а именно импорты)

2023-06-22 09:10 UTC, DudaGod commented on .eslintrc.js
> +                "@typescript-eslint/no-empty-function": "off",
А, видимо это правило связано с тем, что hermione еще полностью не переписана на ts и в некоторых тестах еще присутствуют пустые функции. Короче временное решение. Выглядит так, что в твоем коде это правило не нужно. При рекомендации использовать конфиг из hermione забыл об этой особенности.

2023-06-22 09:12 UTC, DudaGod commented on .eslintrc.js
> +                "@typescript-eslint/no-explicit-any": "off",
Вроде тоже не юзаешь. Выше ответил.

2023-06-22 09:28 UTC, DudaGod commented on src/setup.ts
> +    const tokenFromEnv = process.env[tokenEnvVarialbe];
> ну здесь же нет конфига. Здесь есть код напрямую. Юзер прямо в коде пишет способ аутентификации. Это не конфиг файл

Да, я в курсе и про это явно написал в предыдущем комменте:
"В данном случае можно сказать, что у нас же нет конфига и мы передаем опции просто в функцию. Но необходимость иметь возможность переопределить что-то в CI все еще остается. И обычно это делается через переменные окружения."

Тут хочется, чтобы пользователь имел возможность переопределить токен в CI. Переопределяются они с помощью переменных окружения. И пользователь должен либо писать код вида: `setup({token: process.env.MY_TOKEN || "token_string"})`. Либо мы ему должны предоставлять переменную окружения, которая переопределит токен.

Как по мне предоставлять для всех одинаковую переменную окружения удобнее.

2023-06-22 09:31 UTC, rprovodenko commented on src/setup.test.ts
> +        expect(process.env.SELENIUM_REMOTE_HEADERS).toBe(`{"Authorization":"OAuth mytoken"}`);
пустые строки. окей, понял

2023-06-22 10:06 UTC, DudaGod commented on src/setup.ts
> +    const tokenFromEnv = process.env[tokenEnvVarialbe];
В чате решили, что переменная окружения не нужна и пусть пользователь пишет код вида - `setup({token: process.env.MY_TOKEN || "token_string"})`

2023-06-22 10:10 UTC, DudaGod commented on src/setup.ts
> +        const path = options.tokenFilePath;
Стоимость строк кода не знаю. В данном случае выглядит как лишнее уточнее. Типа по `options.tokenFilePath` итак понятно, что в ней находится и нет особого смысла загонять в отдельную переменную `path`. Ну и по длине строка вмещается.

Короче не вижу поинтов зачем так делать. Но если тебе так больше нравится, то можешь оставить.

2023-06-22 10:14 UTC, DudaGod commented on src/read-token.ts
> +        console.error(e);
Если хочешь оставить стектрейс то нужно оригинальную ошибку ниже не загонять в literal string, тогда он юзает просто `message`. Я предлагаю убрать этот `console.error` и просто чуть ниже кидать свою ошибку.

2023-06-22 10:14 UTC, DudaGod commented on src/read-token.ts
> +    console.log(`playwright-selenium-oauth: reading token at ${path}`);
Для таких кейсов договорились юзнуть либу `debug`

2023-06-22 10:16 UTC, DudaGod commented on src/setup.test.ts
> +        expect(process.env.SELENIUM_REMOTE_HEADERS).toBe(`{"Authorization":"OAuth mytoken"}`);
Пообщались в чате. В данном случае имел ввиду, что arrage, act и assert обычно разделяют пустыми строками.

2023-06-22 10:19 UTC, DudaGod commented on src/setup.test.ts
> +            `"playwright-selenium-oauth: "token" or "tokenFilePath" or PLAYWRIGHT_SELENIUM_OAUTH_TOKEN env var must be provided"`,
Типа можно выполнить `jest --updateSnapshot` и измененный текст ошибки в исходниках засинкается с тестами?

2023-06-22 15:38 UTC, DudaGod approved these changes
/ok (не забыть померджить коммиты)

2023-06-22 15:38 UTC, DudaGod commented on README.md
> +  await setup({token: process.env.SELENIUM_OAUTH_CI_TOKEN || process.env.SELENIUM_OAUTH_USER_TOKEN}); // example for a CI setup
👍

2023-06-22 15:38 UTC, DudaGod commented on README.md
> +import {setup} from "playwright-selenium-oauth"
Я бы даже в такие примеры пустые строки вставлял, чтобы примеры лучше читались.

2023-06-22 15:38 UTC, DudaGod commented on README.md
> +## Help
Наверное можно было бы данный пример объединить с предыдущими.

2023-06-22 15:38 UTC, DudaGod commented on src/setup.test.ts
> +global.console = <Console>(<unknown>{ warn: jest.fn(), error: jest.fn(), log: jest.fn() });
Вот это забыл поправить. `global.console` не нужно создавать. Нужно использовать `jest.mock`

2023-06-23 09:04 UTC, sipayRT approved these changes

2023-06-23 09:04 UTC, sipayRT commented on README.md
> +1. `npm install playwright-selenium-oauth`
лучше сразу с `-D`

2023-06-23 09:04 UTC, sipayRT commented on README.md
> +  await setup({token: process.env.SELENIUM_OAUTH_CI_TOKEN || process.env.SELENIUM_OAUTH_USER_TOKEN}); // example for a CI setup
я бы группировал все же по типу опций (сначала описание поля token)

2023-06-23 09:04 UTC, sipayRT commented on package.json
> +    "description": "Playwtight helper for Selenium OAuth authentication",
опечатка в слове `Playwtight `

2023-06-23 09:04 UTC, sipayRT commented on src/read-token-from-file.ts
> +            `error reading token from file, path: ${path}. ${help ? `help: ${help}.` : ""} Caused by: ${e}. `,
ну я бы тут предложения попереносил на новые строки. Из плюсов - не будет случая, при котором тебе в help передали предложение с точкой, а ты в конце еще от себя точку добавил. А если последнее предложение перенести, то и после help-а точку можно не ставить

2023-06-23 09:04 UTC, sipayRT commented on src/playwright-selenium-error.ts
> +        super(`[playwright-selenium-oauth] ${message}`);
я бы после закрывающей скобки добавил двоеточие

2023-06-23 09:04 UTC, sipayRT commented on src/setup.test.ts
> +            `"[playwright-selenium-oauth] token is empty"`,
в сообщении не хватает совета что делать дальше. Типа, "проверьте опцию такую-то в вашем конфиге"

2023-06-23 09:04 UTC, sipayRT commented on src/setup.ts
> +const headersEnvVariable = "SELENIUM_REMOTE_HEADERS";
мы такое всегда выносим в отдельный файл `constants`. Из плюсов - невозможно ошибиться в написании переменной. Т.е. эту константу ты используешь и в коде, и сразу в тестах

```javascript
{
  SELENIUM_REMOTE_HEADERS: 'SELENIUM_REMOTE_HEADERS'
}
```

2023-06-23 09:04 UTC, sipayRT commented on src/setup.ts
> +        throw new PlaywrightSeleniumError(`token is empty`);
Здесь тоже не хватает конкретики

2023-06-23 09:35 UTC, merged